server :
  port : 8031
  tomcat :
    accept-count : 10
    max-connections : 5000
    max-threads : 500
spring:
  datasource:
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

  mybatis:
    type-aliases-package: com.cpf.backend.bill.entity,com.cpf.backend.origin.entity,com.cpf.backend.user.entity
    mapper-locations: classpath:mapper/*/*.xml

#  redis:
#    # Redis数据库索引（默认为 0）
#    database: 0
#    # Redis服务器地址
#    host: 119.23.60.40
#    # Redis服务器连接端口
#    port: 6379
#    # Redis 密码
#    password: zc@2605201581
#    jedis:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 8
#        # 连接池中的最大空闲连接
#        max-idle: 100
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 10000
#    # 连接超时时间（毫秒）
#    timeout: 0